#!/bin/sh
#		levels	start	kill
#===================================
# chkconfig:	5	99	10
# description:	calibrate the touch sensor

source /etc/profile.d/tslib.sh

start() {
    if [ ! -e /etc/pointercal ]; then
        printf "Calibrating Touch Sensor "
        /usr/bin/ts_calibrate
        sync && sync
	echo "OK"
    fi
}

case "$1" in
  start)
	start
	;;
  stop)
	;;
  restart|reload)
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
