#! /bin/sh
#
# shfldemoinit  Initialize the cinematicexperience to run the Shufflemaster demo
#
source /etc/profile
export DISPLAY=:0

case "$1" in
        start)
                /usr/bin/Qt5_CinematicExperience > /dev/null 2>/dev/null &
                sleep 1
                killall Qt5_CinematicExperience
                sleep 1
                /usr/bin/Qt5_CinematicExperience > /dev/null 2>/dev/null &
                ;;
        stop)
                killall Qt5_CinematicExperience 
                ;;
        *)
                echo "Usage: shfldemoinit {start|stop}" >&2
                exit 1
                ;;
esac

exit 0
