#!/bin/sh
# *** PUT YOUR DESIRED INIT IN THIS FILE ***
#
### BEGIN INIT INFO
# Provides: xserver
# Required-Start: $local_fs $remote_fs dbus
# Required-Stop: $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

killproc() {            # kill the named process(es)
        pid=`/bin/pidof $1`
        [ "$pid" != "" ] && kill $pid
}

case "$1" in
  start)
       . /etc/profile
       username=root
       echo "Starting Xserver"
       /usr/bin/startx&
  ;;

  stop)
        echo "Stopping XServer"
        killproc Xfbdev
  ;;

  restart)
       $0 stop
        sleep 1
        $0 start
  ;;

  *)
        echo "usage: $0 { start | stop | restart }"
  ;;
esac

exit 0
