#!/bin/sh
#==================================================
#
# updated: 03/22/20 Reach Technology
#
# this script controls a system critical function
# and must not be put under control of chkconfig
#
#==================================================

PATH="/sbin:/bin:/usr/sbin:/usr/bin"

# Kill all processes.
echo "Sending all processes the TERM signal..."
killall5 -15
sleep 5
echo "Sending all processes the KILL signal..."
killall5 -9

# We start update here, since we just killed it.
test -x /sbin/update && update

echo "Entering single-user mode..."
exec init -t1 S
