#! /bin/sh 
### BEGIN INIT INFO
# Provides:		rng-tools
# Required-Start:	$syslog
# Required-Stop:	$syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Hardware TRNG daemon
# Description:		Seeds /dev/random using a hardware entropy source
### END INIT INFO

rngd=/usr/sbin/rngd
test -x "$rngd" || exit 1

if [ -e /etc/default/rng-tools ]; then
    . /etc/default/rng-tools
fi

if [ -n "$RNG_DEVICE" ]; then
    EXTRA_ARGS="-- -r $RNG_DEVICE -q"
fi


case "$1" in
  start)
    echo -n "Starting random number generator daemon"
    start-stop-daemon -S -q -x $rngd $EXTRA_ARGS
    echo "."
    ;;
  stop)
    echo -n "Stopping random number generator daemon"
    start-stop-daemon -K -q -n rngd
    echo "."
    ;;
  reload|force-reload)
    echo -n "Signalling rng daemon restart"
    start-stop-daemon -K -q -s 1 -x $rngd
    start-stop-daemon -K -q -s 1 -x $rngd
    ;;
  restart)
    echo -n "Stopping random number generator daemon"
    start-stop-daemon -K -q -n rngd
    echo "."
    echo -n "Starting random number generator daemon"
    start-stop-daemon -S -q -x $rngd $EXTRA_ARGS
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/rng-tools {start|stop|reload|restart|force-reload}"
    exit 1
esac

exit 0
