#! /bin/sh
#
# shfldemoinit  Initialize the cinematicexperience to run the Shufflemaster demo
#
source /etc/profile
export DISPLAY=:0
export QMLVIEWER=/usr/bin/qt5/qmlscene
export MAINVIEW=/application/src/mainview.qml

case "$1" in
        start)
                echo "Starting QMLViewer: " ${QMLVIEWER} ${MAINVIEW}
	            echo ""
                ${QMLVIEWER} -platform eglfs ${MAINVIEW} > /dev/null 2>/dev/null &
				sleep 3
                killall qmlscene
				sleep 3
                ${QMLVIEWER} ${MAINVIEW} > /dev/null 2>/dev/null &
                ;;
        stop)
                killall qmlscene
                ;;
        *)
                echo "Usage: shfldemoinit {start|stop}" >&2
                exit 1
                ;;
esac

exit 0
