#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sys /sys
mkdir /dev/shm
chmod 777 /dev/shm
mount -t tmpfs shm /dev/shm
mount -t tmpfs run /run
mkdir /run/lock
dbus-uuidgen --ensure
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

if [ ! -f /etc/pointercal ]; then
      /usr/bin/ts_calibrate
fi

#
# Collect all the S scripts in /etc/rcS.d and execute them
#

for i in /etc/rcS.d/S*
do
  $i start
done



ifup -a
httpd -p 80 -h /www/pages/

