#!/bin/sh
#

XSERVER=/usr/bin/Xorg

. /etc/profile

if [ -e "$TSLIB_TSDEVICE" ]; then
	if [ ! -f /etc/pointercal ]; then
		/usr/bin/ts_calibrate
	fi
fi

ARGS=" -br -pn -verbose -logverbose -noreset"
APP="/application/bin/qml-viewer"

DISPLAY=':0'

exec xinit $APP -- $XSERVER $DISPLAY $ARGS $*
