#!/bin/sh

global.hostname=g2s
#eth0.serverip=

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=none
#global.dhcp.vendor_id=barebox-mx53-sellwood

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.serverip=a.b.c.d

# can be either 'nfs', 'tftp', 'nor' or 'nand'
kernel_loc=disk
# can be either 'net', 'nor', 'nand' or 'initrd'
rootfs_loc=disk

# can be either 'jffs2' or 'ubifs'
rootfs_type=ext3
rootfs_part_linux_dev=mmcblk0p2
rootfsimage=root-${global.hostname}.$rootfs_type

kernel_part=disk0.0
kernelimage_type=zimage

kernelimage=linuximage
#kernelimage=uImage-${global.hostname}
#kernelimage=Image-${global.hostname}
#kernelimage=Image-${global.hostname}.lzo

if [ -n $user ]; then
	kernelimage="$user"-"$kernelimage"
	nfsroot="$eth0.serverip:/home/$user/nfsroot/${global.hostname}"
	rootfsimage="$user"-"$rootfsimage"
else
	nfsroot="$eth0.serverip:/home/reach/Ptxdist/projects/rootfs"
fi

autoboot_timeout=3

# nec
lvds="video=mxcdi0fb:RGB24,R-VGA ldb=single,di=0,ch0_map=JEIDA"
panel="panel=60,1024,768,15384,220,40,21,7,60,10,0,0,1"

bootargs="console=ttymxc0,115200 di0_primary $lvds $panel hdmi"

disk_parts="256k(barebox),128k(bareboxenv),4M(kernel),-(root)"
nor_parts="256k(barebox),128k(bareboxenv),3M(kernel)"

# set a fancy prompt (if support is compiled in)
PS1="\e[1;32mbarebox@\e[1;31m\h:\w\e[0m "
