#!/bin/bash
#
XSERVER=/usr/bin/Xorg
ARGS=" -br -pn -logverbose -s 0 -noreset -nocursor -nolisten inet6"
export DISPLAY=':0'

case "$1" in
  start)
    echo "starting X11 server"
    . /etc/profile

    $XSERVER $DISPLAY $ARGS &
    xhost +
  ;;
  stop)
    killall Xorg
  ;;
  restart)
    $0 stop
    sleep 1
    $0 start
  ;;
esac

exit 0
