#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin
USB=/mnt

do_mount_usb() {
found=0
for i in /dev/sda?;do
	if [ $i == "/dev/sda?" ];then
		break
	fi
	mount $i ${USB} 2>/dev/null

	if [ $? != 0 ];then 
		continue
	fi

	return 0
done
}

do_start() {
    # wait until the device node is created
    echo "Checking for application software"
    echo "---------------------------------"
    echo "  "

    while [ 1 ];do
	    echo "Waiting for USB Pen..."
	    sleep 3

        do_mount_usb
	    if [ $? == 0 ];then
		    break
	    fi
    done

    echo " "
    echo "Starting Software Update"
    echo "------------------------"

    swupdate -i "${USB}/*.swu" -v

    if [ $? == 0 ];then
	    echo "SUCCESS !"
    else
	    echo "FAILURE !"
    fi

    # reset the update flag
    /sbin/fw_setenv swupdate false

    echo "Rebooting the system!"
    #sleep 5
    #reboot
}

do_stop() {
    echo "Nothing to stop"
}

case "$1" in
start)
	do_start
	;;
stop)
	do_stop || exit $?
	;;
*)
	echo "Usage: $0 {start|stop}" >&2
	exit 3
	;;
esac

