#! /bin/sh
#
# tsinit 	Initialize the touchscreen
#

case "$1" in
	start|"")
		test "$VERBOSE" != no && echo "Initializing touchscreen..."
		# test to see if the sitronix controller is present
		if i2cget -y 1 0x55 0x00 &> /dev/null; then
			# if so load sitronix module
			test "$VERBOSE" != no && echo Using sitronix touchscreen
			modprobe sitronix_i2c_touch
                elif i2cget -y 1 0x38 0x00 &> /dev/null; then
			# if so load evervision module
			test "$VERBOSE" != no && echo Using evervision touchscreen
			modprobe evervision
		else
			# otherwise load mxs module
			test "$VERBOSE" != no && echo Using mxs touchscreen module
			modprobe mxs-ts
		fi
		;;
	stop)
		test "$VERBOSE" != no && echo "Disabling touchscreen..."
		# test to see if the sitronix controller is present
		if i2cget -y 1 0x55 0x00 &> /dev/null; then
			# if so unload sitronix module
			#rmmod sitronix_i2c_touch
			echo "removing sitronix touch"
		else
			# otherwise unload mxs module
			#rmmod mxs-ts
			echo "removing mxs-ts touch"
		fi
		;;
	*)
		echo "Usage: tsinit {start|stop}" >&2
		exit 1
		;;
esac

exit 0
