#!/bin/sh

set -e

WORKDIR=/application/bin
QTAPP=qml-viewer
#DISPLAY_ROT="-display Transformed:Rot90:0"

case "$1" in
  start | debug)
	echo "Starting qt application"
	if [ -f /etc/profile.d/tslib.sh ]; then
		source /etc/profile.d/tslib.sh
	fi
	if [ -e "$TSLIB_TSDEVICE" ]; then
		if [ ! -f /etc/pointercal ]; then
			/usr/bin/ts_calibrate
		fi
	fi

# create links for non-QtE lib names so old Qt code will run
	if [ ! -e /usr/lib/libQtCore.so.4 ]; then
		ln -s /usr/lib/libQt3SupportE.so.4 /usr/lib/libQt3Support.so.4
		ln -s /usr/lib/libQtScriptE.so.4 /usr/lib/libQtScript.so.4
		ln -s /usr/lib/libQtCLuceneE.so.4 /usr/lib/libQtCLucene.so.4
		ln -s /usr/lib/libQtScriptToolsE.so.4 /usr/lib/libQtScriptTools.so.4
		ln -s /usr/lib/libQtCoreE.so.4 /usr/lib/libQtCore.so.4
		ln -s /usr/lib/libQtSqlE.so.4 /usr/lib/libQtSql.so.4
		ln -s /usr/lib/libQtDBusE.so.4 /usr/lib/libQtDBus.so.4
		ln -s /usr/lib/libQtSvgE.so.4 /usr/lib/libQtSvg.so.4
		ln -s /usr/lib/libQtDeclarativeE.so.4 /usr/lib/libQtDeclarative.so.4
		ln -s /usr/lib/libQtTestE.so.4 /usr/lib/libQtTest.so.4
		ln -s /usr/lib/libQtGuiE.so.4 /usr/lib/libQtGui.so.4
		ln -s /usr/lib/libQtWebKitE.so.4 /usr/lib/libQtWebKit.so.4
		ln -s /usr/lib/libQtHelpE.so.4 /usr/lib/libQtHelp.so.4
		ln -s /usr/lib/libQtXmlE.so.4 /usr/lib/libQtXml.so.4
		ln -s /usr/lib/libQtMultimediaE.so.4 /usr/lib/libQtMultimedia.so.4
		ln -s /usr/lib/libQtXmlPatternsE.so.4 /usr/lib/libQtXmlPatterns.so.4
		ln -s /usr/lib/libQtNetworkE.so.4 /usr/lib/libQtNetwork.so.4
	fi

	cd $WORKDIR
        if [ "$1" = "start" ]; then
         QWS_MOUSE_PROTO=tslib:$TSLIB_TSDEVICE ./$QTAPP $DISPLAY_ROT -qws &> /dev/null &
        else
         QWS_MOUSE_PROTO=tslib:$TSLIB_TSDEVICE ./$QTAPP $DISPLAY_ROT -qws &
        fi
        ;;
  stop)
	echo "Stopping qt application"
	killall $QTAPP
	;;
  restart)
	$0 stop
	$0 start
	;;
  *)
	echo "usage: $0 { start | stop | restart }" >&2
	exit 1
	;;
esac

exit 0
