#!/bin/sh

set -e

WORKDIR=/application/bin
QTAPP=qml-viewer
#DISPLAY_ROT="-display Transformed:Rot90:0"

case "$1" in
  start)
	echo "Starting qt application"
	if [ -f /etc/profile.d/tslib.sh ]; then
		source /etc/profile.d/tslib.sh
	fi
	if [ -e "$TSLIB_TSDEVICE" ]; then
		if [ ! -f /etc/pointercal ]; then
			/usr/bin/ts_calibrate
		fi
	fi

	cd $WORKDIR
	QWS_MOUSE_PROTO=tslib:$TSLIB_TSDEVICE ./$QTAPP $DISPLAY_ROT -platform eglfs &> /dev/null &
	;;
  stop)
	echo "Stopping qt application"
	killall $QTAPP
	;;
  restart)
	$0 stop
	$0 start
	;;
  *)
	echo "usage: $0 { start | stop | restart }" >&2
	exit 1
	;;
esac

exit 0
