#!/bin/sh

if type psplash-write >/dev/null 2>&1; then
        TMPDIR=/mnt/.psplash psplash-write "QUIT" || true
fi

dbus-uuidgen > /etc/machine-id

set -e

if [ -f /etc/profile.d/qml-viewer.sh ]; then
	source /etc/profile.d/qml-viewer.sh
fi

if [ -f /etc/profile.d/tslib.sh ]; then
        source /etc/profile.d/tslib.sh
fi

WORKDIR=/usr/share/reach/bin
QTAPP=qml-viewer
#DISPLAY_ROT="-display Transformed:Rot90:0"
SOUND="$(cat /proc/asound/cards)"     

case "$1" in
  start | debug)
        if [[ "$SOUND" =~ "no soundcards" ]]; then
        echo "Using dummy audio module."    
          modprobe snd_dummy;   
        fi
    
        echo "Starting qt application" 
	cd $WORKDIR
	if [ "$1" = "start" ]; then
          ./$QTAPP $DISPLAY_ROT -plugin TOUCH_PLUGIN &> /dev/null &
        else
          ./$QTAPP $DISPLAY_ROT -plugin TOUCH_PLUGIN &
        fi
        ;;
  stop)
	echo "Stopping qt application"
	killall $QTAPP
	;;
  restart)
	$0 stop
	$0 start
	;;
  *)
	echo "usage: $0 { start | stop | restart }" >&2
	exit 1
	;;
esac

exit 0
