#!/bin/sh

SIO_AGENT=/application/bin/sio-agent
SIO_TTY=#SIOTTY#
SIO_BAUD="115200"

case "$1" in
start | debug)
	# show this during quiet boot too.
	echo "starting SIO Agent..." >&2
        if ["$1" = "start"]; then
	  start-stop-daemon -m -p /var/run/sio_agent.pid -b -a $SIO_AGENT -S -- -t $SIO_TTY -b $SIO_BAUD
        else
          $SIO_AGENT -t $SIO_TTY -b $SIO_BAUD &
          echo $! > /var/run/io_agent.pid
        fi
        ;;
stop)
	echo "stoping SIO Agent..."
	start-stop-daemon -p /var/run/sio_agent.pid -K
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: /etc/init.d/sio_agent{start|debug|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
