#!/bin/sh

TIO_AGENT=/application/bin/tio-agent
TIO_ARGS="-v -r"

case "$1" in
start | debug)
	# show this during quiet boot too.
	echo "starting TIO Agent..." >&2
	if [ "$1" = "start" ]; then
          start-stop-daemon -m -p /var/run/tio_agent.pid -b -a $TIO_AGENT -S -- $TIO_ARGS
        else
          $TIO_AGENT $TIO_ARGS &
          echo $! > /var/run/tio_agent.pid
        fi
        ;;
stop)
	echo "stoping TIO Agent..."
	start-stop-daemon -p /var/run/tio_agent.pid -K
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: /etc/init.d/tio_agent{start|debug|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
